<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class MvmController extends Controller
{
    public function workouts() { return DB::table('workouts')->join('exercises', 'workouts.exercise_id', '=', 'exercises.id')->leftJoin('workout_sets', 'workout_sets.workout_id', '=', 'workouts.id')->select('workouts.id', 'workouts.name', 'workouts.date', 'workouts.category', 'workouts.tags', 'exercises.name as exercise', 'workout_sets.weight', 'workout_sets.reps')->orderByDesc('workouts.date')->get()->map(fn ($item) => [...(array) $item, 'tags' => json_decode($item->tags ?? '[]')]); }
    public function storeWorkout(Request $request) { $data = $request->validate(['name' => ['required', 'string', 'max:100'], 'exercise' => ['required', 'string', 'max:255'], 'weight' => ['required', 'numeric', 'min:0'], 'reps' => ['required', 'integer', 'min:1'], 'date' => ['required', 'date'], 'category' => ['nullable', 'string', 'max:100'], 'tags' => ['array']]); $exerciseId = DB::table('exercises')->where('name', $data['exercise'])->value('id') ?? DB::table('exercises')->insertGetId(['name' => $data['exercise'], 'created_at' => now()]); $workoutId = DB::table('workouts')->insertGetId(['name' => $data['name'], 'exercise_id' => $exerciseId, 'date' => $data['date'], 'category' => $data['category'] ?? null, 'tags' => json_encode($data['tags'] ?? [])]); DB::table('workout_sets')->insert(['workout_id' => $workoutId, 'weight' => $data['weight'], 'reps' => $data['reps']]); return response()->json(['id' => $workoutId], 201); }
    public function metrics() { return DB::table('body_metrics')->orderByDesc('recorded_at')->get()->map(fn ($metric) => ['id' => $metric->id, 'weight' => $metric->weight, 'date' => $metric->recorded_at]); }
    public function storeMetric(Request $request) { $data = $request->validate(['weight' => ['required', 'numeric', 'min:0'], 'date' => ['required', 'date']]); $id = DB::table('body_metrics')->insertGetId(['weight' => $data['weight'], 'recorded_at' => $data['date']]); return response()->json(['id' => $id], 201); }
    public function plans() { return DB::table('training_plans')->orderBy('day_of_week')->get()->map(fn ($plan) => ['id' => $plan->id, 'day' => $plan->day_of_week, 'title' => $plan->title]); }
    public function storePlan(Request $request) { $data = $request->validate(['day' => ['required', 'integer', 'between:0,6'], 'title' => ['required', 'string', 'max:100']]); $id = DB::table('training_plans')->insertGetId(['day_of_week' => $data['day'], 'title' => $data['title'], 'created_at' => now(), 'updated_at' => now()]); return response()->json(['id' => $id], 201); }
    public function updatePlan(Request $request, int $id) { $data = $request->validate(['day' => ['required', 'integer', 'between:0,6'], 'title' => ['required', 'string', 'max:100']]); DB::table('training_plans')->where('id', $id)->update(['day_of_week' => $data['day'], 'title' => $data['title'], 'updated_at' => now()]); return response()->json(['id' => $id]); }
    public function deletePlan(int $id) { DB::table('training_plans')->where('id', $id)->delete(); return response()->noContent(); }
    public function events() { return DB::table('schedule_events')->orderBy('start_date')->get()->map(fn ($event) => ['id' => $event->id, 'title' => $event->title, 'start' => $event->start_date, 'end' => $event->end_date]); }
    public function storeEvent(Request $request) { $data = $request->validate(['title' => ['required', 'string', 'max:255'], 'start' => ['required', 'date'], 'end' => ['nullable', 'date']]); $id = DB::table('schedule_events')->insertGetId(['title' => $data['title'], 'start_date' => $data['start'], 'end_date' => $data['end'] ?? null, 'created_at' => now(), 'updated_at' => now()]); return response()->json(['id' => $id], 201); }
    public function updateEvent(Request $request, int $id) { $data = $request->validate(['title' => ['required', 'string', 'max:255'], 'start' => ['required', 'date'], 'end' => ['nullable', 'date']]); DB::table('schedule_events')->where('id', $id)->update(['title' => $data['title'], 'start_date' => $data['start'], 'end_date' => $data['end'] ?? null, 'updated_at' => now()]); return response()->json(['id' => $id]); }
    public function deleteEvent(int $id) { DB::table('schedule_events')->where('id', $id)->delete(); return response()->noContent(); }
    public function videos() { return DB::table('reference_videos')->latest()->get()->map(fn ($video) => ['id' => $video->id, 'title' => $video->title, 'url' => $video->url, 'category' => $video->category, 'thumbnail' => $video->thumbnail_url]); }
    public function storeVideo(Request $request) { $data = $request->validate(['title' => ['required', 'string', 'max:255'], 'url' => ['required', 'url'], 'category' => ['nullable', 'string', 'max:100'], 'thumbnail' => ['nullable', 'url']]); $id = DB::table('reference_videos')->insertGetId(['title' => $data['title'], 'url' => $data['url'], 'category' => $data['category'] ?? null, 'thumbnail_url' => $data['thumbnail'] ?? null, 'created_at' => now(), 'updated_at' => now()]); return response()->json(['id' => $id], 201); }
}
